In [1]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_diabetes
import numpy as np
import pickle

In [9]:
X, y = load_diabetes(return_X_y=True)

In [8]:
X.shape

(442, 10)

In [4]:
y.shape

(442,)

In [5]:
X = X[:, 0].reshape(-1, 1) # Берём только один признак и переведем строку в столбец

In [11]:
X[0]

array([ 0.03807591,  0.05068012,  0.06169621,  0.02187235, -0.0442235 ,
       -0.03482076, -0.04340085, -0.00259226,  0.01990842, -0.01764613])

In [19]:
regressor = LinearRegression()
regressor.fit(X,y)

LinearRegression()

In [20]:
value_to_predict = np.array([0.04]).reshape(-1, 1)
regressor.predict(value_to_predict)

array([164.30080714])

In [21]:
with open('myfile.pkl', 'wb') as output:
   	pickle.dump(regressor, output) #Сохраняем

with open('myfile.pkl', 'rb') as pkl_file:
    	regressor_from_file = pickle.load(pkl_file) #Загружаем

In [24]:
regressor_from_file.predict(np.array([0]).reshape(-1, 1))

array([152.13348416])